### ISSUE TITLE
Campo de CPF e CNPJ

### ISSUE THREAD

**Issue by tsabaia** [gerencianet/gn-api-whmcs#1]
Muitas pessoas que usam WHMCS não colocam um campo dedicado a CPF e outro CNPJ, usam apenas um campo e o cliente preenche com CPF se for PF ou CNPJ se for PJ. Seria interessante o modulo suportar um único campo desses 2 documentos.

**Comment by FilipeMata** [comment]
Bom dia, Thiago!

Na próxima atualização que será disponibilizada para o módulo este quesito estará implementado. No momento, os dois campos estão sendo utilizados devido à uma exigência da API Gerencianet de que ambos os campos fossem passados para compras como Pessoa Jurídica. Felizmente, isto não é mais necessário. Assim, a charge poderá ser gerada considerando apenas um documento.
Saliento que assim que as atualizações estiverem disponíveis, te notificarei através deste post.

Agradeço pela sugestão, e quaisquer outras sugestões são muito bem vindas.

**Comment by tsabaia** [comment]
Ótimo, fico no aguardo dessa atualização.

Outra sugestão é referente a opção da pessoa definir o ID do campo/ordem onde esta esse documento ao invés de ser pelo nome do campo, já que nem todo mundo coloca o mesmo nome nesses campos.

**Comment by MarksEliel** [comment]
Será Ótimo!

**Comment by FilipeMata** [comment]
Boa tarde Thiago e Marcos!

Conforme prometido, venho através deste post lhes notificar a respeito da ultima atualização do módulo oficial da Gerencianet para o WHMCS. Nesta ultima versão não são necessários 2 campos para coletar os dados de CPF e CNPJ do cliente. Os demais campos como "Juridica" e "Razao Social" também não existem mais nessa atualização. Como você havia sugerido Thiago, esta nova atualização permite que o próprio usuário administrador informe o campo que ele gerou no WHMCS para coletar CPF e/ou CNPJ.
Outras funcionalidade que foram adicionadas à esta nova versão envolvem um design responsivo para a tela de erros retornada ao usuário, quando algo não foi preenchido corretamente, e a adição de taxas próprias do WHMCS, quando existem, ao boleto gerencianet. 

Agradecemos as sugestões e a paciência.

**Comment by tsabaia** [comment]
ótimo
