### ISSUE TITLE
Pagamento divergente

### ISSUE THREAD

**Issue by jhowlive** [gerencianet/gn-api-whmcs#10]
Olá!
Se eu ativar o modo de Debug para ver os logs do módulo, toda vez que um boleto é pago, nos logs aparece a mensagem "Divergent Payment"
Porém a cobrança está certa, e o WHMCS confirma o pagamento corretamente.

**Comment by tiagoxpl** [comment]
@jhowlive 

Me chamo Tiago e sou da equipe de Consultoria Técnica em Integrações da Gerencianet.

Por envolver requisições da API que estão presentes em sua conta Gerencianet, além de possuir informações pessoais (como dados cadastrais), o ideal é que você efetue login em sua conta Gerencianet e abra um ticket para interagir com o nosso suporte. Dessa forma, vamos conseguir verificar como as requisições estão sendo trabalhadas entre WHMCS/Módulo/API. Por aqui não é possível localizar seu cadastro conosco.

Caso precise de orientações sobre como abrir tickets, por favor, acesse: https://dev.gerencianet.com.br/docs/fale-conosco

Não esqueça de fornecer o máximo de informações no ticket, como por exemplo, versão do PHP, versão do WHMCS, qual o módulo Gerencianet está usando (da Gerencianet, do Gofas ou do Edvan), print da tela de configurações do módulo, número da(s) transação(ões) envolvida(s) e demais informações que julgar pertinentes.

Qualquer coisa, estou à disposição para ajudar no que for necessário.
