### ISSUE TITLE
Adicionar Campo para fixa taxa para cobrar do cliente por boleto gerado

### ISSUE THREAD

**Issue by henriquelucas** [gerencianet/gn-api-whmcs#11]
Existe a possibilidade de adicionar uma campo para que seja adicionando uma taxa adicional.
Exemplo não qeuria ta pagando o valor cobrado pela Gerencia Net por cada boleto gerado, queria que essa taxa fosse repassada para o cliente.

**Comment by tiagoxpl** [comment]
@henriquelucas 

Esta prática não é possível. O consumidor não deve ser cobrado por nenhuma tarifa de emissão de boleto bancário. Saiba mais em https://gerencianet.com.br/blog/e-permitido-cobrar-taxas-de-emissao-de-boleto-do-cliente-199
