### ISSUE TITLE
Fix compatibility with PHP 7.1

### ISSUE THREAD

**Issue by rbaldasso** [gerencianet/gn-api-whmcs#12]
The Guzzle's Emitter.php file isn't compatible with php 7.1. There was a pull request on the original repo to fix this. Please add the updated Emitter.php file:

https://github.com/guzzle/guzzle/blob/5.3/src/Event/Emitter.php

PR: https://github.com/guzzle/guzzle/pull/1393/files#diff-f1dfb6a53edf5498ac59acb9347ceb30

**Comment by jvoliveiraGN** [comment]
Oi @rbaldasso tudo bem? 😄 
A atualização do módulo está em fase de testes!
Em breve iremos disponibilizar a atualização contemplando essa compatibilidade.
