### ISSUE TITLE
Cartão de Crédito - GerenciaNet

### ISSUE THREAD

**Issue by MarksEliel** [gerencianet/gn-api-whmcs#2]
Olá, quando estará disponível a opção de cartão de crédito nesta API para WHMCS?

**Comment by tsabaia** [comment]
Esse módulo é apenas para boleto,  para cartão de crédito tem que ser um módulo separado, caso contrário vai perder a função de boleto direto e a vantagem de o cliente escolher direto na fatura se quer cartão ou boleto ao invés de ter que ser na página da gerencianet. 

Seria ótimo a criação de um módulo separado voltado apenas para cartão, de preferencia com checkout transparente. É algo difícil encontrar hoje em dia para WHMCS, com um módulo transparente para cartão acredito que muita gente assim como eu passaria usar o gerencianet como forma principal para cartão ao invés do PagSeguro.

**Comment by FilipeMata** [comment]
Boa tarde pessoal,

A ideia de um módulo da Gerencianet voltado apenas para pagamentos via cartão está sendo estudada pelos setores de desenvolvimento e análise da Gerencianet. Assim que tivermos uma resposta, repassaremos a vocês. Caso surjam outras dúvidas e sugestões, nos envie um ticket através de gerencianet.com.br.

**Comment by ThSantosRS** [comment]
Realmente seria de muito ajuda nas vendas do WHMCS via cartão de crédito com checkout transparente, atualmente não existe essa possibilidade no Brasil.

**Comment by brunowebmasterr** [comment]
Ajudaria muito, seria muito interessante ter-lo no whmcs, facilitaria muito as coisas.

**Comment by mauriciogofas** [comment]
Apoio a criação de um módulo para cartão de crédito , tornaria o Gerencianet referência de checkout transparente para WHMCS.

**Comment by solonalbuquerque** [comment]
Muita gente utiliza isto. Seria interessante mesmo o checkout transparente!

**Comment by tsabaia** [comment]
Filipe, seria uma boa vocês lançarem uma enquete aos clientes, perguntando que utilizaria o modulo transparente para cartão no WHMCS, assim dava para ter uma ideia do retorno que vocês teriam. 

Essa pratica da enquete é legal não só com o WHMCS como outras plataformas que também são carente de módulos.

**Comment by FilipeMata** [comment]
Bom dia pessoal, 

Repassei esta demanda ao nosso setor de análise, que é responsável por gerenciar as transações por cartão de crédito na empresa. A situação já está sendo analisada considerando todas as medidas de segurança que o WHMCS pode ou não nos fornecer para um possível módulo de integração da Gerencianet para transações via cartão de crédito. 

Caso vocês queiram retirar mais dúvidas à respeito deste assunto, sugiro que entrem em contato com o nosso suporte em [https://gerencianet.com.br/central-de-ajuda/](url)

**Comment by tiagoxpl** [comment]
Pessoal, o @mauriciogofas desenvolveu um módulo Gerencianet que permite pagamento por cartão de crédito. Caso queiram verificar, acessem o link: https://gofas.net/whmcs/modulo-gerencianet-cartao-para-whmcs-checkout-transparente-e-pagamento-recorrente
