### ISSUE TITLE
Limite para Pagamentos

### ISSUE THREAD

**Issue by MarksEliel** [gerencianet/gn-api-whmcs#3]
Olá, seria interessante e bastante funcional um campo onde o admin pudesse escolher qual o valor minimo que a fatura deve ter para que a forma de pagamento GerenciaNet apareça nas opções.

**Comment by tsabaia** [comment]
Para que ele apareça na escolha de formas de pagamento acredito que não seja possivel devido as limitações do WHMCS, o que é possivel é eles fazerem uma forma que esconda aquele botão do boleto e exiba uma mensagem informando o valor minimo. 

Porém acho mais interessante a opção de isenção de tarifa a partir de x valor, dessa forma você pode repassar a tarifa para boletos pequenos e isentar em boletos maiores.

**Comment by MarksEliel** [comment]
Bom também @tsabaia ...

**Comment by tsabaia** [comment]
https://github.com/gerencianet/gn-api-whmcs/issues/4

Agora entendi a necessidade de ocultar o boleto para valores abaixo de X, mais um voto pela implementação do recurso de limitar o boleto

**Comment by FilipeMata** [comment]
Bom dia pessoal,

Na verdade esta opção já existe na API da Gerencianet. Temos um valor minimo pré definido para gerar os boletos, e este valor é de R$5,00. Se um cliente tentar efetuar um pagamento de R$ 4,00, por exemplo, uma mensagem de erro será exibida para ele.

**Comment by tsabaia** [comment]
Sim, porém não é algo personalizável como ocorre em outros módulos.

**Comment by MarksEliel** [comment]
Verdade @tsabaia, seria bastante importante adicionar esta opção, sendo assim liberaria para pagamento acima de 20,00 por exemplo...
Imagine que tenhamos um plano de 10,00 o cliente escolhe paga via boleto, e a taxa levaria basicamente a metade do dinheiro, com essa função integrada ao módulo isso não ocorreria...

**Comment by FilipeMata** [comment]
Boa tarde pessoal!

Como solicitado, acabamos de subir uma nova atualização para o módulo contendo um campo que limita o valor da fatura para a geração de boletos pela Gerencianet. Agradecemos as sugestões e a paciência.

**Comment by MarksEliel** [comment]
Ótimo!
