### ISSUE TITLE
Tarifa do Boleto

### ISSUE THREAD

**Issue by tsabaia** [gerencianet/gn-api-whmcs#4]
Olá,
Acabei de instalar o modulo aqui para testar após ser notificado que já estava disponível a atualização da parte do CPF e acabei identificando um erro na tarifa do boleto.

Nas minhas configurações do gerencianet coloquei a tarifa de R$ 1, porém ao gerar o boleto por esse novo modulo essa tarifa não é adicionada ao boleto como ocorre no modulo antigo.

Fico no aguardo da solução desse problema e uma outra sugestão, oferecer a possibilidade de isenção dessa tarifa para boletos acima de X valor.

**Comment by FilipeMata** [comment]
Boa tarde Thiago!

A qual tarifa/campo você se refere? 
Na configuração do módulo WHMCS com a nova API da Gerencianet é configurado um desconto exclusivo para os boletos da Gerencianet. Seria este o campo à que você se refere?

**Comment by tsabaia** [comment]
Não tem nada a ver com desconto.

Me refiro a tarifa de emissão do boleto http://i.imgur.com/aHUX0Oq.png

Veja aqui esse boleto de exemplo, emitido pelo modulo antigo http://i.imgur.com/tFKIJQZ.png

**Comment by FilipeMata** [comment]
Bom dia Thiago!

Este repasse de tarifa a que você se refere era parte do módulo Fortunus, a antiga plataforma para emissão de boletos da Gerencianet. No entanto esta funcionalidade foi descontinuada com o lançamento da nova API de integração, devido à uma exigência do Banco Central. Para saber mais detalhes sobre o assunto, acesse o [link](https://gerencianet.com.br/blog/e-permitido-cobrar-taxas-de-emissao-de-boleto-do-cliente-199/) .

Você também pode entrar em contato conosco no site gerencianet.com.br ou  através do telefone 0800 941 2343.

**Comment by tsabaia** [comment]
Ah sim, agora entendo o motivo do pessoal pedindo tanto por aqui como no Portal do Host a opção de desabilitar o boleto para valores menores que X.
