### ISSUE TITLE
E-mail de Pagamento Confirmado

### ISSUE THREAD

**Issue by tsabaia** [gerencianet/gn-api-whmcs#5]
Sempre que um pagamento é confirmado no WHMCS, o cliente recebe um e-mail alertando isso. Porém com esse novo modulo da gerencianet isso não está ocorrendo, o pagamento é confirmado normalmente via retorno automatico, porém o cliente não recebe o e-mail de pagamento confirmado.

No modulo antigo, quando o retorno automatico funcionava, o cliente recebia o e-mail normalmente.

**Obs.:** Não é aquele e-mail de cobrança da gerencianet, é o proprio e-mail de confirmação do WHMCS

**Comment by FilipeMata** [comment]
Bom dia, @tsabaia !

Agradeço por você ter me alertado a respeito disso. Realmente faltou esta funcionalidade no novo módulo. No entanto, saliento que, na próxima atualização que for disponibilizada para o módulo, esta funcionalidade estará presente.

**Comment by FilipeMata** [comment]
Bom dia, @tsabaia !

Como prometido, saiu hoje uma atualização do módulo Gerencianet com o envio automático de e-mail de confirmação de pagamento por parte do WHMCS. 

Agradecemos a sugestão.

**Comment by tsabaia** [comment]
Apliquei a atualização ontem e corrigiu o erro do email confirmação do pagamento, porém identifiquei um outro problema:

Quando o cliente paga o boleto e os dados é retornado ao WHMCS é apenas adicionado o valor a fatura, ela internamente continua em aberto. 

Notei isso pois tive alguns clientes que tiveram o serviço suspenso mesmo após o pagamento do boleto.

Se você fizer o teste irá verificar. 

Quando você confirma um pagamento manualmente ou por um outro gateway, a data do próximo vencimento é alterada para o próximo ciclo seguinte, como o próximo mês por exemplo. 
imagens de exemplo de um pagamento confirmado corretamente pelo paypal: http://imgur.com/a/IAZXi (repare que o mês de vencimento é o seguinte e não o atual)

Quando o pagamento é retornado do gerencianet para o WHMCS essa mudança no vencimento não é realizada, fazendo com que o serviço seja suspenso após passar o vencimento e consequentemente impedindo a geração automática da fatura do mês seguinte. 

Imagens de exemplo: http://imgur.com/a/HQfiu (repare que o vencimento permanece o mesmo mês).

Estou tendo que acessar diariamente agora o WHMCS, excluindo a translação do Gerencianet e confirmando a fatura normalmente para o cliente não ter a surpresa do serviço suspenso.

**Comment by tsabaia** [comment]
além disso o retorno não aparece na página gatewaylog.php do WHMCS, como acontece com outros modulos inclusive o antigo da gerencianet para WHMCS.

**Comment by FilipeMata** [comment]
Boa tarde, @tsabaia !

Dentro de alguns minutos irei atualizar a versão do módulo considerando os reparos que você sugeriu com relação à data de vencimento. No que diz respeito ao registro da notificação de pagamento nos logs do gateway, só é possível quando você marca a opção 'debug' na configuração do módulo.

**Comment by FilipeMata** [comment]
Boa tarde, @tsabaia 

O módulo foi atualizado. Agradecemos a sugestão.

**Comment by tsabaia** [comment]
Bom dia,
Fiz a atualização dos arquivos ontem a tarde e aguardei virar o dia para algum boleto ser compensado e testar. Agora o pagamento retornado ao WHMCS está sendo. Acessei a API do Gerencianet, fui na opção de notificações e ela está com falha 500, tentei reenviar a notificação e o erro repete.

**Comment by FilipeMata** [comment]
Bom dia @tsabaia !

Atualizei o módulo mais uma vez, corrigindo este erro. Caso surjam outras dúvidas, só falar.

**Comment by tsabaia** [comment]
Agora está funcionando corretamente. Obrigado.

Esperei alguns dias para dar o feedback para olhar o comportamento com clientes, valores e tipos de faturas diferentes(unica, mensal, semestral, fundos).
