### ISSUE TITLE
Cancelamento de fatura e transações da API

### ISSUE THREAD

**Issue by leosmeira** [gerencianet/gn-api-whmcs#6]
Eu cancelei a fatura no WHMCS e o registro da transação na API ainda continua com o status "Aguardando".

Este registro não deveria ser cancelado ?

WHMCS v6.3.1
PHP v5.6
gn-api-whmcs (Master 22/09/2016)

![captura de tela 2016-09-22 as 14 08 05](https://cloud.githubusercontent.com/assets/611966/18758424/70c8ad1e-80ce-11e6-8a89-8a4038e8f630.png)

**Comment by FilipeMata** [comment]
Bom dia @leosmeira 

Nas versões anteriores a versão 0.2.6 do módulo Gerencianet/WHMCS o recurso de cancelamento automático na Gerencianet não estava disponível. Portanto, sugerimos que você atualize o módulo para a versão 0.2.6 e siga as instruções de instalação e configuração do módulo, presentes na documentação do mesmo.

**Comment by leosmeira** [comment]
Ocorreu o seguinte erro ao tentar criar uma fatura(rascunho) ou no momento de cancelar a mesma.
```
Fatal error: Uncaught exception 'Exception' with message 'DateInterval::__construct(): Unknown or bad format (PD)' in /var/www/vhosts/meusite.com.br/subdominios/whmcs/includes/hooks/gerencianet.php:79 Stack trace: #0 /var/www/vhosts/meusite.com.br/subdominios/whmcs/includes/hooks/gerencianet.php(79): DateInterval->__construct('PD') #1 [internal function]: gerencianetUpdateBillet(Array) #2 /var/www/vhosts/meusite.com.br/subdominios/whmcs/includes/hookfunctions.php(0): call_user_func('gerencianetUpda...', Array) #3 /var/www/vhosts/meusite.com.br/subdominios/whmcs/includes/invoicefunctions.php(0): run_hook() #4 /var/www/vhosts/meusite.com.br/subdominios/whmcs/admin/invoices.php(0): updateInvoiceTotal() #5 {main} Next exception 'Exception' with message 'DateInterval::__construct(): Unknown or bad format (PD)' in /var/www/vhosts/meusite.com.br/subdominios/whmcs/includes/classes/WHMCS/Terminus.php:0 Stack trace: #0 [internal function]: WHMCS\Terminus->whmcsExceptionHandler(Object(Excep in /var/www/vhosts/meusite.com.br/subdominios/whmcs/includes/classes/WHMCS/Terminus.php on line 0
```

**Comment by FilipeMata** [comment]
Boa tarde @leosmeira 
Acabei de subir uma versão corrigindo este erro. Peço, por gentileza, que teste a versão 0.2.7.
Caso surjam outros problemas me comunique, por favor.

**Comment by leosmeira** [comment]
A alteração da data de vencimento está funcionando corretamente, mas ao cancelar o meu boleto, a transação da API continua com o status de "Aguardando".

**Comment by FilipeMata** [comment]
Bom dia @leosmeira 
Testei o cancelamento algumas vezes e obtive sucesso em todas elas. O problema no cancelamento da sua fatura pode estar relacionado à outro fator. Para que possamos entender melhor o problema, peço que você tire um print do histórico de requisições da sua aplicação, e nos envie via ticket tal print junto com o número da fatura no whmcs. Nosso suporte técnico irá analisar o que está ocorrendo e lhe responderá o mas breve possível.

**Comment by leosmeira** [comment]
Realizei novos testes e as faturas foram todas canceladas.

Obrigado.
