### ISSUE TITLE
Definição de Multa e Juros

### ISSUE THREAD

**Issue by leosmeira** [gerencianet/gn-api-whmcs#7]
A integração com a API não está enviando informações de Multa e Juros e isso impossibilita a geração de Segunda via pelo site da GerenciaNet.

Seria interessante incluir estes campos para configuração do Portal de Pagamento no WHMCS.

http://screencast.com/t/r5wHM2laUxHB

**Comment by FilipeMata** [comment]
Boa tarde @leosmeira 
Como sugerido, as configurações de juros e multas estão presentes na ultima atualização do módulo Gerencianet/WHMCS.

**Comment by leosmeira** [comment]
Os campos de multa e juros não aparecem após a instalação da versão 0.2.8

**Comment by FilipeMata** [comment]
Boa tarde @leosmeira 

Peço que você nos envie, através de um ticket no portal da Gerencianet ou de sua conta, um print da tela de configurações do seu módulo. Demais erros que estejam ocorrendo devem ser relatados através deste mesmo ticket. Uma vez enviado, será mais fácil para a nossa equipe identificar o problema.
Aguardo retorno.
