### ISSUE TITLE
Adicionar Taxas de Transação

### ISSUE THREAD

**Issue by jhowlive** [gerencianet/gn-api-whmcs#8]
Olá!
Seria muito bom o módulo permitir o usuário definir o quanto paga por cada boleto na Gerencianet.
Lembrando que me refiro ao campo "Transaction Fee" ou "Taxas de Transação" do WHMCS onde é possível definir o quanto custa para a empresa a transação em questão, sem exibir ao cliente ou cobrar do mesmo.
http://imgur.com/N4xN5MU

Obrigado

**Comment by tiagoxpl** [comment]
@jhowlive 

Me chamo Tiago e sou da equipe de Consultoria Técnica em Integrações da Gerencianet.

Nosso módulo oficial atualmente não oferece este recurso, porém, vou deixar registrado internamente sua mensagem como uma sugestão.

Cabe frisar que possuímos dois parceiros oficiais que também desenvolvem seus próprios módulos Gerencianet para o WHMCS; é o Maurício Gofas e o Edvan (eles são citados em nossa [documentação](https://dev.gerencianet.com.br/docs/whmcs) também). Conversando com o Gofas, ele mencionou que no módulo de boletos que desenvolveu há sim este recurso que você quer. O admin define o fee_/boleto nas configurações do módulo. Caso tenha interesse, sugiro que [visite o site do módulo dele](https://gofas.net/whmcs/modulo-gerencianet-boleto-para-whmcs/) e verifique por gentileza.

Qualquer coisa, estou à disposição.
