### ISSUE TITLE
Atualizar vencimento automaticamente

### ISSUE THREAD

**Issue by jhowlive** [gerencianet/gn-api-whmcs#9]
Uma outra sugestão que tenho:
Já que agora é possível editar o vencimento do boleto ao alterar o da fatura, seria interessante disponibilizar uma opção para que caso o boleto esteja vencido, atualizar para o dia atual.
Falo em disponibilizar via opção, pois caso isso seja feito, não creio que seja possível cobrar juros ou multa do cliente, tendo em vista que ele não utilizará a ferramenta de atualização de boletos da Gerencianet, e pelo que sei não é possível alterar o valor do boleto via API para incluir as multas.
Para mim não teria problema, pois adiciono os juros na próxima fatura, mas como nem todos trabalham assim, seria interessante adicionar como uma funcionalidade opcional.

**Comment by tiagoxpl** [comment]
@jhowlive 

Me chamo Tiago e sou da equipe de Consultoria Técnica em Integrações da Gerencianet.

No caso, é preciso realizar um estudo sobre os hooks que são disponibilizados pelo próprio WHMCS, e posteriormente analisar a viabilidade (ou não) de implementação. De qualquer maneira, deixei registrado sua sugestão. Muito obrigado pela contribuição!

Qualquer coisa, estou à disposição.
